---
title: "Análisis de datos de COVID-19 en Costa Rica - Gráficos del paquete base"
author: "Bryan Ramirez"
date: '2022-05-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Presentacion  
Este documento presenta graficos generados a partir de los datos de COVID-19 en Costa Rica, compartidos en el Ministeiro de salud en [https://geovision.uned.ac.cr/oges/](https://geovision.uned.ac.cr/oges/)


## Entradas  
```{r carga-datos}
covid <- read.csv(file = "05_10_22_CSV_GENERAL.csv", sep = ";")
```


## Procesamiento  

## Opciones generales  
```{r opciones-generales}
options(scipen = 7)
```

###Curacion de datos
```{r conversion-fecha}
covid$FECHA <- as.Date(covid$FECHA, format = "%d/%m/%Y")
```


## Salidas  

### Graficos  

#### Casos Acumulados  

#### Positivos  

```{r Casos-Positivos_acumulados}
plot(
  covid$FECHA,
  covid$positivos,
  main = "Casos acumulados poitivps de COVID-19 en Costa Rica",
  xlab = "Fecha",
  ylab = "Casos"
)
```

